
Using cuda device
Traceback (most recent call last):
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/wrappers/monitoring/video_recorder.py", line 55, in __init__
    import moviepy  # noqa: F401
ModuleNotFoundError: No module named 'moviepy'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home-mscluster/abrickhill/RR/cluster/../environment/trainwandb.py", line 35, in <module>
    model.learn(
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/ppo/ppo.py", line 315, in learn
    return super().learn(
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 287, in learn
    total_timesteps, callback = self._setup_learn(
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 68, in reset
    self.start_video_recorder()
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 76, in start_video_recorder
    self.video_recorder = video_recorder.VideoRecorder(
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/wrappers/monitoring/video_recorder.py", line 57, in __init__
    raise error.DependencyNotInstalled(
gymnasium.error.DependencyNotInstalled: moviepy is not installed, run `pip install moviepy`