
Using cuda device
/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "/home-mscluster/abrickhill/RR/cluster/../environment/trainwandb.py", line 35, in <module>
    model.learn(
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/ppo/ppo.py", line 315, in learn
    return super().learn(
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 287, in learn
    total_timesteps, callback = self._setup_learn(
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 68, in reset
    self.start_video_recorder()
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 80, in start_video_recorder
    self.video_recorder.capture_frame()
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/wrappers/monitoring/video_recorder.py", line 113, in capture_frame
    frame = self.env.render()
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 103, in render
    return super().render(mode=mode)
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 255, in render
    images = self.get_images()
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 94, in get_images
    return [env.render() for env in self.envs]  # type: ignore[misc]
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 94, in <listcomp>
    return [env.render() for env in self.envs]  # type: ignore[misc]
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/core.py", line 471, in render
    return self.env.render()
  File "/home-mscluster/abrickhill/RR/environment/handover_env.py", line 384, in render
    return self.robot_env.render()
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 409, in render
    return self.mujoco_renderer.render(
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 646, in render
    viewer = self._get_viewer(render_mode=render_mode)
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 686, in _get_viewer
    self.viewer = OffScreenViewer(self.model, self.data)
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 144, in __init__
    super().__init__(model, data, width, height)
  File "/home-mscluster/abrickhill/anaconda3/envs/handover/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 61, in __init__
    self.con = mujoco.MjrContext(self.model, mujoco.mjtFontScale.mjFONTSCALE_150)
mujoco.FatalError: gladLoadGL error